//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampveEtkinlikkWebSiteBitirme.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCampVeEventEntities : DbContext
    {
        public DBCampVeEventEntities()
            : base("name=DBCampVeEventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hakkimda> Hakkimda { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<YeniKayit> YeniKayit { get; set; }
        public virtual DbSet<tblMisafir> tblMisafir { get; set; }
        public virtual DbSet<tblRezervasyon> tblRezervasyon { get; set; }
        public virtual DbSet<tblMesaj> tblMesaj { get; set; }
    }
}
