//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampveEtkinlikkWebSiteBitirme.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRezervasyon
    {
        public int RezervasyonID { get; set; }
        public Nullable<int> Misafir { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public string Kisi { get; set; }
        public Nullable<int> Oda { get; set; }
        public Nullable<int> Kisi1 { get; set; }
        public Nullable<int> Kisi2 { get; set; }
        public Nullable<int> Kisi3 { get; set; }
        public string RezervasyonadSoyad { get; set; }
        public string Telefon { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual tblMisafir tblMisafir { get; set; }
    }
}
